name: 🐛 Bug Report
description: File a bug report.
labels: [bug]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Providing a self-contained, concise code example that can be used to reproduce the issue.
        Can help to solve the problem as fast as possible.

        For more complex issues provide a repo with the smallest sample that reproduces the bug.

        Avoid including business logic or unrelated code, it makes diagnosis more difficult.
        The code sample should be an SSCCE. See http://sscce.org/ for details.
        In short, please provide a code sample that we can copy/paste, run and reproduce.
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      render: 'shell'
      description: |
        Please include full errors, uncaught exceptions, stack traces.
        Trigger the issue with WebUI's debug build to add relevant logs.
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Possible Solution
      description: If you can suggest fix, include a prototype/workaround/sketch/reference.
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: Please provide the current WebUI version you are using.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details (OS name, version, etc.)
      render: shell
      description: |
        To fill in this section, you can use on Unix-like systems:
        ```sh
        uname -somr
        ```
        On Windows you can use:
        ```sh
        cmd /c wmic cpu get systemname,caption
        ```
    validations:
      required: true
