name: Lint

on:
  workflow_call:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Verify formatting
        run: ~/v/v fmt -verify ~/.vmodules/vwebui && exit 0 || ~/v/v fmt -diff ~/.vmodules/vwebui && exit 1

  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Vet
        run: ~/v/v vet -W ~/.vmodules/vwebui
