name: macOS

on:
  workflow_call:

env:
  MOD_NAME: vwebui

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.MOD_NAME }}
      - name: Setup WebUI library
        run: |
          ${{ env.MOD_NAME }}/setup.vsh
          mv ${{ env.MOD_NAME }} ~/.vmodules/${{ env.MOD_NAME }}
      - name: Cache
        uses: actions/cache/save@v3
        with:
          path: |
            vlang
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  build-examples:
    needs: setup
    strategy:
      matrix:
        compiler: [clang]
        optimization: ['', -prod]
      fail-fast: false
    runs-on: macos-latest
    steps:
      - name: Restore V Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            vlang
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        uses: vlang/setup-v@v1.3
      - name: Build
        run: |
          cd $HOME/.vmodules/${{ env.MOD_NAME }}/examples
          v -cg -cc ${{ matrix.compiler }} ${{ matrix.optimization }} minimal.v
          v -cg -cc ${{ matrix.compiler }} ${{ matrix.optimization }} kiosk.v
          v -cg -cc ${{ matrix.compiler }} ${{ matrix.optimization }} call_js_from_v.v
          v -cg -cc ${{ matrix.compiler }} ${{ matrix.optimization }} call_v_from_js.v
          v -cg -cc ${{ matrix.compiler }} ${{ matrix.optimization }} simple_example.v
          v -cg -cc ${{ matrix.compiler }} ${{ matrix.optimization }} text-editor/
          v -cg -cc ${{ matrix.compiler }} ${{ matrix.optimization }} serve_a_folder/
